# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "390bd89f0367a51cc80c1f8bc8f942d0"
name = "SKU Bulk Generator"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
