export const initialDuplicateSummary = {
  totalSkusScanned: "1,842",
  lastScanDate: "May 20, 2025",
  lastScanTime: "10:30 AM",
  duplicateGroups: 18,
  affectingSkusTotal: 96,
  exactDuplicates: 42,
  affectingExactSkus: 42,
  potentialDuplicates: 54,
  affectingPotentialSkus: 54,
};

export const initialScanSummary = {
  startTime: "May 20, 2025 10:30 AM",
  scanType: "Full inventory scan",
  totalProducts: "1,842",
  totalVariants: "2,756",
  scanDuration: "2m 34s",
  status: "Completed",
};

export const initialDuplicateGroups = [
  {
    id: "group-001",
    groupTag: "#G-001",
    title: "T-Shirt - Black - M",
    duplicateType: "Exact match",
    duplicateTypeDesc: "Identical SKUs",
    severity: "High",
    status: "Needs review",
    affectedSkusCount: "5 SKUs",
    affectedProductsCount: "5 products",
    exampleSku: "TSHIRT-BLK-M",
    moreCount: "+4 more",
    iconType: "shirt",
    iconBg: "bg-orange-light",
    iconColor: "#EA580C",
    records: [
      { id: "rec-101", product: "Classic Cotton T-Shirt", variant: "Black / Medium", productId: "PROD-101", variantId: "VAR-101", currentSku: "TSHIRT-BLK-M", status: "Active" },
      { id: "rec-102", product: "Vintage Black Tee", variant: "Black / Medium", productId: "PROD-102", variantId: "VAR-102", currentSku: "TSHIRT-BLK-M", status: "Active" },
      { id: "rec-103", product: "Essential Crewneck", variant: "Black / Medium", productId: "PROD-103", variantId: "VAR-103", currentSku: "TSHIRT-BLK-M", status: "Active" },
      { id: "rec-104", product: "Organic Cotton Tee", variant: "Black / Medium", productId: "PROD-104", variantId: "VAR-104", currentSku: "TSHIRT-BLK-M", status: "Active" },
      { id: "rec-105", product: "Heavyweight T-Shirt", variant: "Black / Medium", productId: "PROD-105", variantId: "VAR-105", currentSku: "TSHIRT-BLK-M", status: "Active" },
    ],
  },
  {
    id: "group-002",
    groupTag: "#G-002",
    title: "Canvas Tote Bag",
    duplicateType: "Potential match",
    duplicateTypeDesc: "Similar SKUs",
    severity: "Medium",
    status: "Needs review",
    affectedSkusCount: "6 SKUs",
    affectedProductsCount: "6 products",
    exampleSku: "TOTE-CANVAS",
    moreCount: "+5 more",
    iconType: "bag",
    iconBg: "bg-green-light",
    iconColor: "#16A34A",
    records: [
      { id: "rec-201", product: "Eco Canvas Tote Bag", variant: "Natural / OS", productId: "PROD-201", variantId: "VAR-201", currentSku: "TOTE-CANVAS", status: "Active" },
      { id: "rec-202", product: "Heavy Duty Tote", variant: "Natural / OS", productId: "PROD-202", variantId: "VAR-202", currentSku: "TOTE_CANVAS", status: "Active" },
      { id: "rec-203", product: "Market Tote Bag", variant: "Natural / OS", productId: "PROD-203", variantId: "VAR-203", currentSku: "tote-canvas", status: "Active" },
    ],
  },
  {
    id: "group-003",
    groupTag: "#G-003",
    title: "Ceramic Mug - White",
    duplicateType: "Exact match",
    duplicateTypeDesc: "Identical SKUs",
    severity: "High",
    status: "Needs review",
    affectedSkusCount: "3 SKUs",
    affectedProductsCount: "3 products",
    exampleSku: "MUG-WHT-11OZ",
    moreCount: "+2 more",
    iconType: "mug",
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
    records: [
      { id: "rec-301", product: "Standard Coffee Mug 11oz", variant: "White", productId: "PROD-301", variantId: "VAR-301", currentSku: "MUG-WHT-11OZ", status: "Active" },
      { id: "rec-302", product: "Ceramic Drinkware Mug", variant: "White", productId: "PROD-302", variantId: "VAR-302", currentSku: "MUG-WHT-11OZ", status: "Active" },
      { id: "rec-303", product: "Office Coffee Cup", variant: "White", productId: "PROD-303", variantId: "VAR-303", currentSku: "MUG-WHT-11OZ", status: "Active" },
    ],
  },
  {
    id: "group-004",
    groupTag: "#G-004",
    title: "Baseball Cap - Black",
    duplicateType: "Potential match",
    duplicateTypeDesc: "Similar SKUs",
    severity: "Low",
    status: "Needs review",
    affectedSkusCount: "4 SKUs",
    affectedProductsCount: "4 products",
    exampleSku: "CAP-BLK-OS",
    moreCount: "+3 more",
    iconType: "cap",
    iconBg: "bg-purple-light",
    iconColor: "#7C3AED",
    records: [
      { id: "rec-401", product: "Unstructured Dad Hat", variant: "Black", productId: "PROD-401", variantId: "VAR-401", currentSku: "CAP-BLK-OS", status: "Active" },
      { id: "rec-402", product: "Snapback Cap", variant: "Black", productId: "PROD-402", variantId: "VAR-402", currentSku: "CAP-BLK", status: "Active" },
    ],
  },
  {
    id: "group-005",
    groupTag: "#G-005",
    title: "Stainless Steel Bottle",
    duplicateType: "Potential match",
    duplicateTypeDesc: "Similar SKUs",
    severity: "Low",
    status: "Needs review",
    affectedSkusCount: "2 SKUs",
    affectedProductsCount: "2 products",
    exampleSku: "BOTTLE-SS-500",
    moreCount: "+1 more",
    iconType: "bottle",
    iconBg: "bg-red-light",
    iconColor: "#DC2626",
    records: [
      { id: "rec-501", product: "Insulated Water Bottle 500ml", variant: "Silver", productId: "PROD-501", variantId: "VAR-501", currentSku: "BOTTLE-SS-500", status: "Active" },
      { id: "rec-502", product: "Thermal Hydration Flask", variant: "Silver", productId: "PROD-502", variantId: "VAR-502", currentSku: "BOTTLE-SS-500", status: "Active" },
    ],
  },
];
