export const kpiData = [
  {
    id: "credits",
    title: "Credits used",
    value: "40",
    suffix: "/ 100",
    subtext: "Resets on May 20, 2025",
    iconType: "wallet",
    progress: 40,
  },
  {
    id: "products",
    title: "Total products",
    value: "78",
    subtext: "In your store",
    iconType: "bag",
  },
  {
    id: "variants",
    title: "Total variants",
    value: "93",
    subtext: "Across all products",
    iconType: "layers",
  },
  {
    id: "skus",
    title: "SKUs generated",
    value: "1,245",
    subtext: "All time",
    iconType: "sparkle",
  },
];

export const chartData = [
  { date: "May 14", skus: 45 },
  { date: "May 15", skus: 42 },
  { date: "May 16", skus: 145 },
  { date: "May 17", skus: 100 },
  { date: "May 18", skus: 55 },
  { date: "May 19", skus: 105 },
  { date: "May 20", skus: 170 },
];

export const quickActionsData = [
  {
    id: "generate-skus",
    title: "Generate SKUs",
    description: "Create new SKU rules",
    iconType: "userWand",
    route: "/app/generate-sku",
  },
  {
    id: "view-history",
    title: "View history",
    description: "Track all generated SKUs",
    iconType: "history",
    route: "/app/generate-history",
  },
  {
    id: "automations",
    title: "Automations",
    description: "Manage automated rules",
    iconType: "automations",
    badge: "Pro",
    route: "/app/auto-sku",
  },
  {
    id: "duplicate-skus",
    title: "Duplicate SKUs",
    description: "Find and resolve duplicates",
    iconType: "duplicate",
    badge: "Pro",
    route: "/app/duplicated-sku",
  },
];

export const recentActivityData = [
  {
    id: "1",
    rule: "Daily new products",
    status: "Completed",
    products: 12,
    variants: 18,
    generated: 30,
    date: "May 20, 2025 10:30 AM",
  },
  {
    id: "2",
    rule: "Collection based rule",
    status: "Completed",
    products: 8,
    variants: 24,
    generated: 32,
    date: "May 19, 2025 09:15 AM",
  },
  {
    id: "3",
    rule: "Vendor rule",
    status: "Completed",
    products: 15,
    variants: 27,
    generated: 42,
    date: "May 18, 2025 02:45 PM",
  },
  {
    id: "4",
    rule: "Manual run",
    status: "Failed",
    products: 5,
    variants: 8,
    generated: "—",
    date: "May 17, 2025 11:20 AM",
    action: "Retry",
  },
  {
    id: "5",
    rule: "Gift cards update",
    status: "Completed",
    products: 3,
    variants: 3,
    generated: 6,
    date: "May 16, 2025 08:10 AM",
  },
];

export const recommendationsData = [
  {
    id: "auto-sku",
    title: "Automated SKU",
    badge: "Pro",
    description: "Auto generate SKUs for new products.",
    actionText: "Set up",
    theme: "purple",
    route: "/app/auto-sku",
    iconType: "bot",
  },
  {
    id: "duplicate-scanner",
    title: "Duplicate scanner",
    badge: "Pro",
    description: "Find and fix duplicate SKUs.",
    actionText: "Scan now",
    theme: "blue",
    route: "/app/duplicated-sku",
    iconType: "scanner",
  },
  {
    id: "custom-rules",
    title: "Custom rules",
    description: "Create advanced rules",
    actionText: "Explore",
    theme: "green",
    route: "/app/generate-sku",
    iconType: "rules",
  },
];
