export const initialAutomationSummary = {
  activeRules: 5,
  totalRulesLimit: 8,
  productsAutomatedThisMonth: "1,248",
  skusGeneratedThisMonth: "2,396",
  lastRunDate: "May 20, 2025",
  lastRunTime: "10:30 AM",
};

export const initialAutomationRules = [
  {
    id: "auto-1",
    name: "New products daily",
    description: "Generate SKU for new products added daily.",
    scope: "All products",
    scopeSubtext: "All collections",
    status: "Active",
    trigger: "New product added",
    lastRunDate: "May 20, 2025",
    lastRunTime: "10:30 AM",
    lastRunStatus: "success",
    skusGenerated: 342,
    skusGeneratedSubtext: "Today",
    iconType: "shirt",
    iconBg: "bg-purple-light",
    iconColor: "#7C3AED",
    config: {
      prefix: "PROD",
      bodyType: "Sequential",
      padding: 4,
      suffix: "MAIN",
      separator: "-",
    },
  },
  {
    id: "auto-2",
    name: "Collection based automation",
    description: "Apply SKU rules to products in specific collections.",
    scope: "Snowboards, Accessories",
    scopeSubtext: "+2 more",
    status: "Active",
    trigger: "Product added to collection",
    lastRunDate: "May 20, 2025",
    lastRunTime: "09:15 AM",
    lastRunStatus: "success",
    skusGenerated: 186,
    skusGeneratedSubtext: "Today",
    iconType: "document",
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
    config: {
      prefix: "SNOW",
      bodyType: "Sequential",
      padding: 4,
      suffix: "2025",
      separator: "_",
    },
  },
  {
    id: "auto-3",
    name: "Vendor automation",
    description: "Generate SKU for products from specific vendors.",
    scope: "Burton, Nitro",
    scopeSubtext: "+3 more",
    status: "Active",
    trigger: "New product added",
    lastRunDate: "May 19, 2025",
    lastRunTime: "08:45 PM",
    lastRunStatus: "success",
    skusGenerated: 278,
    skusGeneratedSubtext: "Yesterday",
    iconType: "tag",
    iconBg: "bg-green-light",
    iconColor: "#16A34A",
    config: {
      prefix: "VND",
      bodyType: "Product ID",
      padding: 0,
      suffix: "AUT",
      separator: "-",
    },
  },
  {
    id: "auto-4",
    name: "Weekend special products",
    description: "Apply special SKU format for weekend launches.",
    scope: "Selected collections",
    scopeSubtext: "2 collections",
    status: "Paused",
    trigger: "Scheduled (Every Fri 6PM)",
    lastRunDate: "May 16, 2025",
    lastRunTime: "06:00 PM",
    lastRunStatus: "success",
    skusGenerated: 124,
    skusGeneratedSubtext: "Last run",
    iconType: "calendar",
    iconBg: "bg-orange-light",
    iconColor: "#EA580C",
    config: {
      prefix: "WKND",
      bodyType: "Sequential",
      padding: 4,
      suffix: "SPEC",
      separator: "-",
    },
  },
  {
    id: "auto-5",
    name: "VIP products automation",
    description: "Auto generate SKU for VIP tagged products.",
    scope: "Products with tag",
    scopeSubtext: "VIP",
    status: "Draft",
    trigger: "New product added",
    lastRunDate: "Never run",
    lastRunTime: "-",
    lastRunStatus: "none",
    skusGenerated: 0,
    skusGeneratedSubtext: "Total",
    iconType: "star",
    iconBg: "bg-purple-light",
    iconColor: "#C026D3",
    config: {
      prefix: "VIP",
      bodyType: "Sequential",
      padding: 4,
      suffix: "PREM",
      separator: "-",
    },
  },
];

export const triggerOptions = [
  { id: "product_created", title: "New product added", desc: "Triggers when a new product is published in your store." },
  { id: "collection_added", title: "Product added to collection", desc: "Triggers when a product is assigned to a target collection." },
  { id: "vendor_added", title: "Vendor matching", desc: "Triggers when a product matches selected vendor names." },
  { id: "scheduled", title: "Scheduled (Recurring)", desc: "Runs on a recurring schedule (e.g. every Friday at 6:00 PM)." },
];

export const scopeOptions = [
  { id: "all_products", label: "All products" },
  { id: "collections", label: "Specific collections" },
  { id: "vendors", label: "Specific vendors" },
  { id: "tags", label: "Product tags" },
];
