export const initialSummaryData = {
  totalExecuted: 24,
  successful: 21,
  successRate: "87.5%",
  failed: 3,
  failureRate: "12.5%",
  lastExecutionDate: "May 20, 2025",
  lastExecutionTime: "10:30 AM",
};

export const initialHistoryRecords = [
  {
    id: "run-001",
    rule: "Daily new products",
    ruleType: "Manual run",
    scope: "All products",
    scopeCount: "12 products",
    products: 12,
    variants: 18,
    generated: 30,
    status: "Completed",
    date: "May 20, 2025",
    time: "10:30 AM",
    creditsUsed: 18,
    settings: {
      prefix: "STRT",
      bodyType: "Sequential",
      padding: 4,
      suffix: "END",
      separator: "-",
    },
    iconBg: "bg-purple-light",
    iconColor: "#5B3DF5",
  },
  {
    id: "run-002",
    rule: "Collection based rule",
    ruleType: "Automated",
    scope: "Snowboards",
    scopeCount: "8 products",
    products: 8,
    variants: 24,
    generated: 32,
    status: "Completed",
    date: "May 19, 2025",
    time: "09:15 AM",
    creditsUsed: 24,
    settings: {
      prefix: "SNOW",
      bodyType: "Sequential",
      padding: 4,
      suffix: "2025",
      separator: "_",
    },
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
  },
  {
    id: "run-003",
    rule: "Vendor rule",
    ruleType: "Automated",
    scope: "Burton",
    scopeCount: "15 products",
    products: 15,
    variants: 27,
    generated: 42,
    status: "Completed",
    date: "May 18, 2025",
    time: "02:45 PM",
    creditsUsed: 27,
    settings: {
      prefix: "BURT",
      bodyType: "Product ID",
      padding: 0,
      suffix: "MAIN",
      separator: "-",
    },
    iconBg: "bg-green-light",
    iconColor: "#16A34A",
  },
  {
    id: "run-004",
    rule: "Manual run - Summer Sale",
    ruleType: "Manual run",
    scope: "Selected products",
    scopeCount: "5 products",
    products: 5,
    variants: 8,
    generated: "—",
    status: "Failed",
    date: "May 17, 2025",
    time: "11:20 AM",
    creditsUsed: 0,
    failureReason: "Some products could not be updated because their generated SKU already exists in the store inventory.",
    failedProductsCount: 2,
    settings: {
      prefix: "SUMM",
      bodyType: "Sequential",
      padding: 4,
      suffix: "SALE",
      separator: "-",
    },
    iconBg: "bg-red-light",
    iconColor: "#DC2626",
  },
  {
    id: "run-005",
    rule: "Gift cards update",
    ruleType: "Manual run",
    scope: "Gift Cards",
    scopeCount: "3 products",
    products: 3,
    variants: 3,
    generated: 6,
    status: "Completed",
    date: "May 16, 2025",
    time: "08:10 AM",
    creditsUsed: 3,
    settings: {
      prefix: "GIFT",
      bodyType: "Sequential",
      padding: 3,
      suffix: "CARD",
      separator: "-",
    },
    iconBg: "bg-purple-light",
    iconColor: "#5B3DF5",
  },
  {
    id: "run-006",
    rule: "Clearance collection",
    ruleType: "Automated",
    scope: "Clearance",
    scopeCount: "10 products",
    products: 10,
    variants: 12,
    generated: "—",
    status: "Failed",
    date: "May 15, 2025",
    time: "04:05 PM",
    creditsUsed: 0,
    failureReason: "Shopify API rate limit exceeded during variant batch update.",
    failedProductsCount: 5,
    settings: {
      prefix: "CLR",
      bodyType: "Random",
      padding: 6,
      suffix: "OUT",
      separator: "|",
    },
    iconBg: "bg-red-light",
    iconColor: "#DC2626",
  },
  {
    id: "run-007",
    rule: "Accessories Auto Rule",
    ruleType: "Automated",
    scope: "Accessories",
    scopeCount: "14 products",
    products: 14,
    variants: 20,
    generated: 34,
    status: "Completed",
    date: "May 14, 2025",
    time: "01:20 PM",
    creditsUsed: 20,
    settings: {
      prefix: "ACC",
      bodyType: "Sequential",
      padding: 4,
      suffix: "SET",
      separator: "-",
    },
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
  },
  {
    id: "run-008",
    rule: "Winter Apparel Batch",
    ruleType: "Bulk generation",
    scope: "Apparel",
    scopeCount: "25 products",
    products: 25,
    variants: 60,
    generated: 85,
    status: "Completed",
    date: "May 13, 2025",
    time: "11:45 AM",
    creditsUsed: 60,
    settings: {
      prefix: "WINT",
      bodyType: "Sequential",
      padding: 4,
      suffix: "APP",
      separator: "-",
    },
    iconBg: "bg-purple-light",
    iconColor: "#5B3DF5",
  },
];

export const sampleGeneratedSkus = {
  "run-001": [
    { product: "The Minimal Snowboard", variant: "Black / 152", sku: "STRT-0001-END", status: "Generated" },
    { product: "The Minimal Snowboard", variant: "Black / 156", sku: "STRT-0002-END", status: "Generated" },
    { product: "The Videographer Snowboard", variant: "Purple / 154", sku: "STRT-0003-END", status: "Generated" },
    { product: "The Videographer Snowboard", variant: "Purple / 158", sku: "STRT-0004-END", status: "Generated" },
    { product: "The Draft Snowboard", variant: "Cyan / 150", sku: "STRT-0005-END", status: "Generated" },
    { product: "The Draft Snowboard", variant: "Cyan / 154", sku: "STRT-0006-END", status: "Generated" },
  ],
  "run-002": [
    { product: "Custom Snowboard Alpha", variant: "Blue / Medium", sku: "SNOW_0001_2025", status: "Generated" },
    { product: "Custom Snowboard Alpha", variant: "Blue / Large", sku: "SNOW_0002_2025", status: "Generated" },
    { product: "Custom Snowboard Beta", variant: "Red / Small", sku: "SNOW_0003_2025", status: "Generated" },
  ],
};
