export const initialPricingData = {
  currentPlan: "Free", // "Free", "Basic", or "Pro"
  billingInterval: "annual", // "monthly" or "annual"
};

export const plans = [
  {
    id: "free",
    name: "Free",
    description: "Essential tools to test and generate basic SKUs for free.",
    iconType: "leaf",
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
    monthlyPrice: 0,
    annualPrice: 0,
    annualMonthlyEquivalent: 0,
    annualSavings: 0,
    buttonText: "Get Started Free",
    buttonVariant: "outline",
    features: [
      "Up to 500 SKUs",
      "1 active rule",
      "Manual SKU generation",
      "Basic SKU preview",
      "Standard community support",
    ],
  },
  {
    id: "basic",
    name: "Basic",
    description: "Perfect for growing stores getting started with SKU management.",
    iconType: "rocket",
    iconBg: "bg-green-light",
    iconColor: "#16A34A",
    monthlyPrice: 9,
    annualPrice: 100,
    annualMonthlyEquivalent: 8.33,
    fullYearMonthlyCost: 108,
    annualSavings: 8,
    buttonText: "Start 3-Day Free Trial",
    buttonVariant: "outline",
    features: [
      "Up to 10,000 SKUs",
      "5 active automation rules",
      "Standard duplicate SKU scan",
      "All custom SKU formats & separators",
      "3-day free trial included",
      "Dedicated email support",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "Unlimited power & features for growing and large stores.",
    isPopular: true,
    badgeText: "★ MOST POPULAR",
    iconType: "crown",
    iconBg: "bg-purple-light",
    iconColor: "#7C3AED",
    monthlyPrice: 19,
    annualPrice: 220,
    annualMonthlyEquivalent: 18.33,
    fullYearMonthlyCost: 228,
    annualSavings: 8,
    buttonText: "Start 3-Day Free Trial",
    buttonVariant: "primary",
    features: [
      "UNLIMITED SKUs",
      "UNLIMITED active automation rules",
      "UNLIMITED automated SKU generation",
      "UNLIMITED duplicate scans & resolutions",
      "Export full audit history (CSV & Excel)",
      "All custom SKU formats & separators",
      "3-day free trial included",
      "Priority dedicated support",
    ],
  },
];

export const comparisonMatrix = [
  { feature: "SKUs limit", free: "Up to 500", basic: "Up to 10,000", pro: "Unlimited" },
  { feature: "Active automation rules", free: "1", basic: "5", pro: "Unlimited" },
  { feature: "Automated SKU generation", free: false, basic: "Included", pro: "Unlimited" },
  { feature: "Duplicate SKU scan & resolve", free: "Basic scan only", basic: "Included", pro: "Unlimited" },
  { feature: "Export audit history", free: false, basic: false, pro: true },
  { feature: "Custom SKU formats & separators", free: false, basic: true, pro: true },
  { feature: "Customer Support", free: "Standard support", basic: "Dedicated email support", pro: "Priority full support" },
];
