export const initialPricingData = {
  currentPlan: "Pro", // Can be "Basic", "Pro", "Advanced", "Enterprise"
  billingInterval: "annual", // "monthly" or "annual"
};

export const plans = [
  {
    id: "basic",
    name: "Basic",
    description: "Perfect for small stores getting started.",
    iconType: "leaf",
    iconBg: "bg-green-light",
    iconColor: "#16A34A",
    monthlyPrice: 11,
    annualMonthlyPrice: 9,
    annualTotalPrice: 108,
    buttonText: "Choose Basic",
    buttonVariant: "outline",
    features: [
      "Up to 5,000 SKUs",
      "5 active rules",
      "1 automated rule",
      "Basic duplicate scan",
      "Email support",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "Best for growing stores that need more power.",
    isPopular: true,
    badgeText: "★ MOST POPULAR",
    iconType: "crown",
    iconBg: "bg-purple-light",
    iconColor: "#7C3AED",
    monthlyPrice: 24,
    annualMonthlyPrice: 19,
    annualTotalPrice: 228,
    strikethroughAnnualTotal: 240,
    buttonText: "Choose Pro",
    buttonVariant: "primary",
    features: [
      "Up to 25,000 SKUs",
      "20 active rules",
      "10 automated rules",
      "Advanced duplicate scan",
      "Priority email support",
      "Export history",
      "Custom separators",
    ],
  },
  {
    id: "advanced",
    name: "Advanced",
    description: "For large stores with advanced requirements.",
    iconType: "rocket",
    iconBg: "bg-orange-light",
    iconColor: "#EA580C",
    monthlyPrice: 49,
    annualMonthlyPrice: 39,
    annualTotalPrice: 468,
    strikethroughAnnualTotal: 480,
    buttonText: "Choose Advanced",
    buttonVariant: "outline",
    features: [
      "Up to 100,000 SKUs",
      "Unlimited active rules",
      "Unlimited automated rules",
      "Advanced duplicate scan",
      "Export history",
      "Custom separators",
      "Priority support",
      "API access",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For enterprise stores with custom needs.",
    iconType: "building",
    iconBg: "bg-blue-light",
    iconColor: "#2563EB",
    isCustom: true,
    customPriceText: "Custom",
    customPriceSubtext: "Custom pricing",
    buttonText: "Contact Sales",
    buttonVariant: "outline",
    features: [
      "Unlimited SKUs",
      "Unlimited rules",
      "Unlimited automated rules",
      "Advanced duplicate scan",
      "Export history",
      "Custom separators",
      "Dedicated account manager",
      "API access",
      "Custom integrations",
    ],
  },
];

export const comparisonMatrix = [
  { feature: "SKUs limit", basic: "Up to 5,000", pro: "Up to 25,000", advanced: "Up to 100,000", enterprise: "Unlimited" },
  { feature: "Active rules", basic: "5", pro: "20", advanced: "Unlimited", enterprise: "Unlimited" },
  { feature: "Automated rules", basic: "1", pro: "10", advanced: "Unlimited", enterprise: "Unlimited" },
  { feature: "Duplicate SKU scan", basic: "Basic", pro: "Advanced", advanced: "Advanced", enterprise: "Advanced" },
  { feature: "Export history", basic: false, pro: true, advanced: true, enterprise: true },
  { feature: "API access", basic: false, pro: false, advanced: true, enterprise: true },
  { feature: "Custom separators", basic: false, pro: true, advanced: true, enterprise: true },
  { feature: "Priority support", basic: false, pro: true, advanced: true, enterprise: true },
];
